---
- name: Dump Fortigate configuration
  hosts: all
  gather_facts: no

  vars:
    config_file: "{{ inventory_hostname }}_config_{{ ansible_date_time.date }}"

  tasks:
    - name: Get Fortigate configuration
      expect:
        command: show full-configuration
        responses:
          'Enter.*': '\r'
          '.* # ': '\r'
      register: fortigate_config

    - name: Save Fortigate configuration to file
      copy:
        content: "{{ fortigate_config.stdout }}"
        dest: "/path/to/config/files/{{ config_file }}"
      register: copy_result

    - name: Print copy result
      debug:
        var: copy_result
