- hosts: all
  gather_facts: no
  connection: local
  collections:
    - fortinet.fortios
  vars:
    host: "{{ ansible_host }}:{{ ansible_port }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    vdom: "root"
    ssl_verify: "False"

  tasks:
  - name: print the vars    
    debug:
      msg: 
      - "{{ansible_host}} , {{test}}"
      - "from inventory file: user = {{ ansible_user }}, password = {{ ansible_password }}, port = {{ ansible_port }}"
      - "from local vars: user = {{ username }}, password = {{ password }}, port = {{ host }}"
      - "timeout = {{ ansible_persistent_connect_timeout }}"
    tags:
    - backup
    - var
    - facts
      
  - name: gather gather all physical and vlan interfaces status facts
    fortios_facts:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      gather_subset:
        - fact: 'system_status_select'
        - fact: 'system_interface_select'
          filters:
            - include_vlan: true
    register: result
    tags:
    - facts

  - name: print the facts    
    debug:
      msg: "{{ ansible_facts.network_resources.system_status_select }}"
    tags:
    - facts

  - name: backup global or a_specific_vdom settings
    connection: httpapi
    fortios_system_config_backup_restore:
      config: "system config backup"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom: "{{ vdom }}"
      backup: "yes"
      https: True
      ssl_verify: False
      scope: "global"
      filename: "/tmp/backup_test{{host}}"
    tags:
    - backup
