- name: Upgrade Fortigate Router
  hosts: fortigate_group
  gather_facts: no
  vars:
    ftp_server: ftp.example.com
    ftp_username: ftpuser
    ftp_password: ftppassword
    firmware_image: fortios.out

  tasks:
  - name: Check free disk space
    fortios_system_info:
      gather_subset: hardware

    register: disk_info

  - name: Abort if not enough free disk space
    fail:
      msg: "Not enough free disk space on {{ inventory_hostname }}"
    when: disk_info.ansible_facts.hardware.memory.free_memory < 104857600

  - name: Copy firmware image to router
    copy:
      src: "{{ firmware_image }}"
      dest: /tmp/
      remote_src: yes
      validate: "sha256sum {{ firmware_image }}"

  - name: Upgrade Firmware
    fortios_system_software:
      src: "/tmp/{{ firmware_image }}"
      upgrade: yes
      reboot: yes

  - name: Wait for router to come back online
    wait_for:
      host: "{{ inventory_hostname }}"
      port: 22
      timeout: 600
