---
- name: Enable internet stuff
  hosts: all
#  hosts: mikrotik
  tasks:
#     - name: Collect all facts from the device
#       community.routeros.facts:
#        gather_subset: hardware
#       register: mikrofacts     
#       when: "'router' in inventory_hostname"
#     - name: Show HW facts on the router
#       ansible.builtin.debug: 
#         var: mikrofacts
#     - name: Print all available facts
#       ansible.builtin.debug:
#         var: ansible_facts

     - name: NxFilter container
       become: yes
       containers.podman.podman_container:
         name: nxfilter
         image: packetworks/nxfilter-base:latest
         restart_policy: always
         publish: 
           - "192.168.83.89:53:53/udp"
           - "192.168.83.89:4439:443"
           - "19002-19004:19002-19004"
         volume:
           - "nxfilter-conf:/nxfilter/conf"
           - "nxfilter-log:/nxfilter/log"
           - "nxfilter-db:/nxfilter/db"
         state: started
       when: "'rhel' in inventory_hostname"

     - name: enable eth5 on mikrotik
       community.routeros.command:
         commands: /interface/ethernet/enable "ether5 - unify"
       when: "'mikrotik' in inventory_hostname"
