---
- name: Upgrade Mikrotik
  hosts: mikrotik
  gather_facts: false
  vars:
    backup_dir: "/home/net_control/backup"
  tasks:
    - name: Check for version
      ansible.builtin.shell: >-
       sshpass -p '{{ ansible_password }}' ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_host }} system/package/update/check-for-updates
      register: update_check
      delegate_to: 192.168.83.89
    
    - name: Print result
      ansible.builtin.debug: 
       var: update_check
    
    - block:
      
      - name: Run backup first
        import_tasks: mikrotik_backup.yml
    
      - name: Pretend to update
        ansible.builtin.shell: >-
         sshpass -p '{{ ansible_password }}' ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_host }} system/package/update/check-for-updates
        register: post_update_check
      - name: email results
        mail:
         host: 192.168.83.3
         port: 25
         to: uros@zajc.net
         from: uzajc@hotmail.com
         subject: Ansible Mikrotik update
         body: |
          This is an ansible email from {{ ansible_hostname }} to let you know the Mikrotik Router has been updated
          Old version:
          {{ update_check }}
          
          New Version
          {{ post_update_check }}

          Cheers bud
        delegate_to: home-pc
      when: '"New Version is available" in update_check.stdout[0]'
