---
- name: start win10 VM
  hosts: hp

- name: Start a VM
  community.libvirt.virt:
    name: win10
    state: running
#    when: '"win10" not in running_vms.stdout[0]'  

# - name: List only running VMs
#   community.libvirt.virt:
#     command: list_vms
#     state: running
#   register: running_vms
