---
- name: Update FortiGate firmware using sshpass
  hosts: fortigate
  vars:
    vdom: "root"
    ssl_verify: "False"
  tasks:
  - name: Check firmware version
    command: "sshpass -p '{{ password }}' fwctl -c get sys firmware"
    register: firmware_info
    debug:
    var: firmware_info
