---
- hosts: fortigate
  vars:
    vdom: "root"
    ssl_verify: "False"
  tasks:
  - name: Check firmware version
    command: "sshpass -p '{{ ansible_backup_password }}' ssh -o StrictHostKeyChecking=no {{ ansible_backup_user }}@{{ inventory_hostname }} fwctl -c get sys firmware"
    register: firmware_info
  - name: Debug firmware_info
    debug:
      var: firmware_info