---
- name: Ansible Create user play
  hosts: home-pc
  become: yes
  tasks:
    - name: Add the user 'svc.ansible' a primary group of 'sudo'
      ansible.builtin.user:
        name: svc.ansible
        comment: Ansible service account
        group: sudo
        createhome: yes        # Defaults to yes
        home: /home/svc.ansible    # Defaults to /home/<username>
        shell: /bin/bash
        password: 'Paste code here' # use mkpasswd --method=sha-512 to generate
