---
- name: Convert Updates to HTML Table
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run apt list command
      shell: "apt list --upgradable"
      register: apt_list_output

    - name: Convert to HTML Table
      set_fact:
        updates_html: |
          <table>
            <tr><th style='font-weight:bold;color:blue;'>Package</th><th style='font-weight:bold;color:blue;'>Version</th></tr>
            {% for line in apt_list_output.stdout_lines %}
              {% if line.startswith("Listing...") %}
                <tr><td colspan="2">{{ line }}</td></tr>
              {% else %}
                <tr>
                  <td>{{ line.split(' ')[0] }}</td>
                  <td>{{ line.split(' ')[-1][1:-1] }}</td>
                </tr>
              {% endif %}
            {% endfor %}
          </table>

    - name: Display HTML Table
      debug:
        var: updates_html
